param(
    [Parameter(Mandatory = $true)]
    [string] $NdkRoot,

    [Parameter(Mandatory = $true)]
    [string] $DobbyRoot,

    [string] $PackageName = "com.fizzd.connectedworlds.leveleditor.debug",
    [string] $AndroidApi = "21",
    [string] $Abi = "arm64-v8a",
    [string] $Configuration = "Release",

    [switch] $CompileJavaExample,
    [string] $AndroidJar = "",
    [string] $UnityClassesJar = "",
    [string] $JavaSource = ""
)

$ErrorActionPreference = "Stop"

if ($Abi -ne "arm64-v8a") {
    throw "Only arm64-v8a is currently supported."
}

$toolchain = Join-Path $NdkRoot "toolchains\llvm\prebuilt\windows-x86_64\bin"
$clang = Join-Path $toolchain "aarch64-linux-android$AndroidApi-clang++.cmd"
if (!(Test-Path -LiteralPath $clang)) {
    $clang = Join-Path $toolchain "aarch64-linux-android$AndroidApi-clang.cmd"
}
if (!(Test-Path -LiteralPath $clang)) {
    throw "Android NDK clang not found under: $NdkRoot"
}

$dobbyInclude = Join-Path $PSScriptRoot "include"
$dobbyLib = Join-Path $DobbyRoot "libdobby.a"
if (!(Test-Path -LiteralPath $dobbyInclude)) {
    throw "Bundled include directory not found: $dobbyInclude"
}
if (!(Test-Path -LiteralPath $dobbyLib)) {
    throw "Dobby static library not found: $dobbyLib"
}

$src = Join-Path $PSScriptRoot "async_input.c"
$officialJudgementSrc = Join-Path $PSScriptRoot "official_judgement.c"
$outDir = Join-Path $PSScriptRoot "out\$Abi"
$out = Join-Path $outDir "libAsyncInput.so"
$generatedConfig = Join-Path $outDir "async_input_config.h"

New-Item -ItemType Directory -Force -Path $outDir | Out-Null
Set-Content -LiteralPath $generatedConfig -Encoding ASCII -Value @(
    "/* Generated by build.ps1. Do not edit. */",
    "#ifndef PACKAGE_NAME",
    "#define PACKAGE_NAME `"$PackageName`"",
    "#endif"
)

if ($Configuration -ieq "Debug") {
    $optFlags = @("-O0", "-g")
} else {
    $optFlags = @("-O2")
}

$commonFlags = @(
    "-shared",
    "-fPIC",
    "-Wall",
    "-Wextra",
    "-Werror",
    "-static-libstdc++",
    "-include", $generatedConfig,
    "-I", $dobbyInclude,
    "-o", $out,
    "-x", "c",
    $src,
    $officialJudgementSrc,
    "-x", "none",
    $dobbyLib,
    "-llog",
    "-ldl"
)

& $clang @optFlags @commonFlags
if ($LASTEXITCODE -ne 0) {
    throw "native build failed with exit code $LASTEXITCODE"
}
Write-Host "[built] $out"

if ($CompileJavaExample) {
    if ($AndroidJar -eq "" -or !(Test-Path -LiteralPath $AndroidJar)) {
        throw "-AndroidJar is required when -CompileJavaExample is set."
    }
    if ($UnityClassesJar -eq "" -or !(Test-Path -LiteralPath $UnityClassesJar)) {
        throw "-UnityClassesJar is required when -CompileJavaExample is set."
    }
    if ($JavaSource -eq "") {
        $JavaSource = Join-Path $PSScriptRoot "java\com\fizzd\connectedworlds\editorport\ExtraMenuUnityPlayerActivity.java"
    }
    if (!(Test-Path -LiteralPath $JavaSource)) {
        throw "Java source not found: $JavaSource"
    }

    $javaOut = Join-Path $PSScriptRoot "out\java_classes"
    New-Item -ItemType Directory -Force -Path $javaOut | Out-Null

    $classpath = "$AndroidJar;$UnityClassesJar"
    & javac -encoding UTF-8 -classpath $classpath -d $javaOut $JavaSource
    if ($LASTEXITCODE -ne 0) {
        throw "Java example build failed with exit code $LASTEXITCODE"
    }
    Write-Host "[built] $javaOut"
}
